# Generated by Django 3.0.4 on 2020-05-05 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lushcloset.core.models.processed_request
import lushcloset.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('date_est_return', models.DateTimeField(validators=[lushcloset.core.validators.validate_date_est_return])),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Listing')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='ProcessedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], default=lushcloset.core.models.processed_request.ApprovalStatus['DISAPPROVED'], max_length=20)),
                ('request_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('NOT_COMPLETED', 'Not completed')], default=lushcloset.core.models.processed_request.RequestStatus['NOT_COMPLETED'], max_length=20)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Request')),
            ],
            options={
                'verbose_name': 'Processed Request',
                'verbose_name_plural': 'Processed Requests',
            },
        ),
    ]
