version: '3'

services:
  django:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_container
    depends_on:
      - postgres
    env_file:
      - ./envs/.env.prod
    ports:
      - "8000:8000"
  postgres:
    container_name: postgres_container
    env_file:
      - ./envs/.env.db.prod
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: